=== zupson/Head_soccer_2D_game/xml/dtd/PlayerProperties.dtd
<!ELEMENT PlayerProperties (PlayerProperty*)>
<!ELEMENT PlayerProperty (PlayerName, Color, PlayerType)>
<!ELEMENT PlayerName (#PCDATA)>
<!ELEMENT Color (#PCDATA)>
<!ELEMENT PlayerType (#PCDATA)>

=== zupson/Head_soccer_2D_game/xml/PlayerProperties.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE PlayerProperties SYSTEM "dtd/PlayerProperties.dtd">
<PlayerProperties>
    <PlayerProperty>
        <PlayerName>eee</PlayerName>
        <Color>0xff00ffff</Color>
        <PlayerType>PLAYER_2</PlayerType>
    </PlayerProperty>
    <PlayerProperty>
        <PlayerName>aaa</PlayerName>
        <Color>0x000080ff</Color>
        <PlayerType>PLAYER_1</PlayerType>
    </PlayerProperty>
    <PlayerProperty>
        <PlayerName>www</PlayerName>
        <Color>0x000080ff</Color>
        <PlayerType>PLAYER_2</PlayerType>
    </PlayerProperty>
    <PlayerProperty>
        <PlayerName>rrr</PlayerName>
        <Color>0x336666ff</Color>
        <PlayerType>PLAYER_1</PlayerType>
    </PlayerProperty>
    <PlayerProperty>
        <PlayerName>qqq</PlayerName>
        <Color>0x000080ff</Color>
        <PlayerType>PLAYER_2</PlayerType>
    </PlayerProperty>
    <PlayerProperty>
        <PlayerName>ttt</PlayerName>
        <Color>0x800000ff</Color>
        <PlayerType>PLAYER_1</PlayerType>
    </PlayerProperty>
</PlayerProperties>
